[build-system]
requires = ["setuptools>=42", "wheel", "Cython>=3.0.0"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["pp*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]