name: Sync to Releases Branch

on:
  push:
    branches:
      - main
  release:
    types: [published, created]
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '0.') || github.event_name == 'workflow_dispatch' || github.event_name == 'release'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          ref: main  # Explicitly checkout main branch
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Sync to releases branch
        run: |
          # Ensure we're on main and it's up to date
          git checkout main
          git pull origin main
          
          # Create or switch to releases branch
          git checkout releases 2>/dev/null || git checkout -b releases
          
          # Reset releases to match main exactly
          git reset --hard main
          
          # Push changes
          git push -f origin releases