name: Build Wheels

on:
  push:
    branches:
      - 'releases'
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: startsWith(github.event.head_commit.message, '0.') || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cythonize: [0, 1]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build cibuildwheel

      - name: Build Cythonized wheels
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64 x86"
          CIBW_BEFORE_ALL_LINUX: "yum install -y python3-devel gcc gcc-c++"
          CIBW_ENVIRONMENT: "CYTHONIZE=1"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_TEST_SKIP: "*"  # Skip all tests
        run: cibuildwheel --output-dir dist

      - uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*.whl