name: Sync to Releases Branch

on:
  push:
    branches:
      - main
  release:
    types: [published, created]
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '0.') || github.event_name == 'workflow_dispatch' || github.event_name == 'release'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Sync to releases branch
        run: |
          # Fetch all branches
          git fetch origin
          # Try to checkout releases branch or create new one
          git checkout releases 2>/dev/null || git checkout -b releases
          # Reset to origin/main
          git reset --hard origin/main
          # Force push to releases
          git push -f origin releases