name: Sync to Releases Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '0.') || github.event_name == 'workflow_dispatch'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Sync to releases branch
        run: |
          git checkout releases || git checkout -b releases
          git reset --hard main
          git push -f origin releases